export const ROUTES = {
  HomeScreen: 'HomeScreen',
  ContactsScreen: 'ContactsScreen',
  ProfileScreen: 'ProfileScreen',
  EditProfileScreen: 'EditProfileScreen',
  ProductDetailsScreen: 'ProductDetailsScreen',
  ProductsScreen: 'ProductsScreen',
  DrawerNavigator: 'DrawerNavigator',
  MainTabs: 'MainTabs',
  ProductsStack: 'ProductsStack',
  ProfileStack: 'ProfileStack',
  ReduxCounterScreen: 'ReduxCounterScreen',
  CameraScreen: 'CameraScreen',
  LocationScreen: 'LocationScreen',
  SensorScreen: 'SensorScreen',
} as const;
